permalink: /:categories/:year/:month/:day/:title/

include: ['_pages']

title: Michael Ge | Software Engineer | Graphic Artist
email: michael.zh.ge@gmail.com
baseurl: ""
url: http://www.geemichael.com
twitter_username: hahakumquat
github_username:  hahakumquat
phone: (626) 893-5895
facebook: https://www.facebook.com/michaelzhge
linkedin: https://www.linkedin.com/in/michael-ge-a9041b9a/
deviantart: https://hahakumquat.deviantart.com/
instagram: https://www.instagram.com/hahakumquat/
github: https://github.com/hahakumquat

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# plugins:
#     - jekyll-minifier

# jekyll-minifier:
#   remove_spaces_inside_tags: true
#   remove_multi_spaces: true
#   remove_comments: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - node_modules
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
