title: Michael Ge | Software Engineer & Graphic Artist
email: contact@geemichael.com
description: Portfolio of Michael Ge featuring software engineering projects
baseurl: ""
url: "https://www.geemichael.com"

author:
  name: Michael Ge

social:
  links:
    - https://github.com/hahakumquat
    - https://linkedin.com/in/michael-ge-a9041b9a

markdown: kramdown
sass:
  style: compressed
  
incremental: true
livereload: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

timezone: America/Los_Angeles
